//! Access `RunCommand` / `AcCmd` constants (Access 97–2010).
//!
//! `From<u16>` never fails: unknown codes become [`AcCmd::Unknown`].

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub enum AcCmd {
    WindowUnhide,
    WindowHide,
    Exit,
    CompactDatabase,
    EncryptDecryptDatabase,
    RepairDatabase,
    MakeMDEFile,
    MoreWindows,
    AppRestore,
    AppMaximize,
    AppMinimize,
    AppMove,
    AppSize,
    DocRestore,
    DocMaximize,
    DocMove,
    DocSize,
    Refresh,
    Font,
    Save,
    SaveAs,
    WindowCascade,
    TileVertically,
    WindowArrangeIcons,
    OpenDatabase,
    NewDatabase,
    OLEDDELinks,
    RecordsGoToNew,
    Replace,
    Find,
    RunMacro,
    PageSetup,
    InsertObject,
    Duplicate,
    AboutMicrosoftAccess,
    FormHdrFtr,
    ReportHdrFtr,
    PasteAppend,
    InsertFile,
    SelectForm,
    TabOrder,
    FieldList,
    AlignLeft,
    AlignRight,
    AlignTop,
    AlignBottom,
    AlignToGrid,
    SizeToGrid,
    Options,
    SelectRecord,
    SortingAndGrouping,
    BringToFront,
    SendToBack,
    PrintPreview,
    ApplyDefault,
    SetControlDefaults,
    OLEObjectDefaultVerb,
    Close,
    SizeToFit,
    DocMinimize,
    ViewRuler,
    SnapToGrid,
    ViewGrid,
    PasteSpecial,
    RecordsGoToNext,
    RecordsGoToPrevious,
    RecordsGoToFirst,
    RecordsGoToLast,
    SizeToFitForm,
    EditingAllowed,
    ClearGrid,
    JoinProperties,
    QueryTotals,
    QueryTypeCrosstab,
    TableNames,
    QueryParameters,
    FormatCells,
    DataEntry,
    HideColumns,
    UnhideColumns,
    DeleteQueryColumn,
    InsertQueryColumn,
    RemoveTable,
    ViewToolbox,
    MacroNames,
    MacroConditions,
    SingleStep,
    QueryTypeSelect,
    QueryTypeUpdate,
    QueryTypeAppend,
    QueryTypeDelete,
    ApplyFilterSort,
    QueryTypeMakeTable,
    LoadFromQuery,
    SaveAsQuery,
    SaveRecord,
    AdvancedFilterSort,
    MicrosoftAccessHelpTopics,
    LinkTables,
    UserAndGroupPermissions,
    UserAndGroupAccounts,
    FreezeColumn,
    UnfreezeAllColumns,
    PrimaryKey,
    SubformDatasheet,
    SelectAllRecords,
    ViewTables,
    ViewQueries,
    ViewForms,
    ViewReports,
    ViewMacros,
    ViewModules,
    RowHeight,
    ColumnWidth,
    InsertFileIntoModule,
    SaveModuleAsText,
    FindPrevious,
    WindowSplit,
    ProcedureDefinition,
    DebugWindow,
    Reset,
    CompileAllModules,
    CompileAndSaveAllModules,
    GoContinue,
    StepOver,
    SetNextStatement,
    ShowNextStatement,
    ToggleBreakpoint,
    ClearAllBreakpoints,
    Relationships,
    NewObjectTable,
    NewObjectQuery,
    NewObjectForm,
    NewObjectReport,
    NewObjectMacro,
    NewObjectModule,
    NewObjectClassModule,
    LayoutPreview,
    SaveAsReport,
    Rename,
    RemoveFilterSort,
    SaveLayout,
    ClearAll,
    HideTable,
    ShowDirectRelationships,
    ShowAllRelationships,
    CreateRelationship,
    EditRelationship,
    Indexes,
    AlignToShortest,
    AlignToTallest,
    SizeToNarrowest,
    SizeToWidest,
    HorizontalSpacingMakeEqual,
    HorizontalSpacingDecrease,
    HorizontalSpacingIncrease,
    VerticalSpacingMakeEqual,
    VerticalSpacingDecrease,
    VerticalSpacingIncrease,
    SortAscending,
    SortDescending,
    ToolbarsCustomize,
    OLEObjectConvert,
    QueryTypeSQLDataDefinition,
    QueryTypeSQLPassThrough,
    ViewCode,
    ConvertDatabase,
    CallStack,
    Send,
    OutputToExcel,
    OutputToRTF,
    OutputToText,
    InvokeBuilder,
    ZoomBox,
    QueryTypeSQLUnion,
    Run,
    PageHdrFtr,
    DesignView,
    SQLView,
    ShowTable,
    CloseWindow,
    InsertRows,
    DeleteRows,
    Cut,
    Copy,
    Paste,
    AutoDial,
    NewObjectAutoForm,
    NewObjectAutoReport,
    WordMailMerge,
    TestValidationRules,
    ControlWizardsToggle,
    End,
    Redo,
    ObjectBrowser,
    AddWatch,
    EditWatch,
    QuickWatch,
    StepToCursor,
    Indent,
    Outdent,
    FilterByForm,
    FilterBySelection,
    ViewLargeIcons,
    ViewDetails,
    ViewSmallIcons,
    ViewList,
    LineUpIcons,
    ArrangeIconsByName,
    ArrangeIconsByType,
    ArrangeIconsByCreated,
    ArrangeIconsByModified,
    ArrangeIconsAuto,
    CreateShortcut,
    ToggleFilter,
    OpenTable,
    InsertPicture,
    DeleteRecord,
    StartupProperties,
    PageNumber,
    DateAndTime,
    ChangeToTextBox,
    ChangeToLabel,
    ChangeToListBox,
    ChangeToComboBox,
    ChangeToCheckBox,
    ChangeToToggleButton,
    ChangeToOptionButton,
    ChangeToImage,
    AnswerWizard,
    MicrosoftOnTheWeb,
    ClearItemDefaults,
    Zoom200,
    Zoom150,
    Zoom100,
    Zoom75,
    Zoom50,
    Zoom25,
    Zoom10,
    FitToWindow,
    PreviewOnePage,
    PreviewTwoPages,
    PreviewFourPages,
    PreviewEightPages,
    PreviewTwelvePages,
    OpenURL,
    OpenStartPage,
    OpenSearchPage,
    RegisterActiveXControls,
    DeleteTab,
    DatabaseProperties,
    Import,
    InsertActiveXControl,
    InsertHyperlink,
    References,
    AutoCorrect,
    InsertProcedure,
    CreateReplica,
    SynchronizeNow,
    RecoverDesignMaster,
    ResolveConflicts,
    DeleteWatch,
    Spelling,
    AutoFormat,
    DeleteTableColumn,
    InsertTableColumn,
    InsertLookupColumn,
    RenameColumn,
    SetDatabasePassword,
    UserLevelSecurityWizard,
    FilterExcludingSelection,
    QuickPrint,
    ConvertMacrosToVisualBasic,
    SaveAllModules,
    FormView,
    DatasheetView,
    AnalyzePerformance,
    AnalyzeTable,
    Documenter,
    TileHorizontally,
    Properties,
    TransparentBackground,
    TransparentBorder,
    CompileLoadedModules,
    InsertLookupField,
    Undo,
    InsertChart,
    GoBack,
    GoForward,
    StopLoadingPage,
    RefreshPage,
    FavoritesOpen,
    FavoritesAddTo,
    ShowOnlyWebToolbar,
    ToolbarControlProperties,
    ShowMembers,
    ListConstants,
    QuickInfo,
    ParameterInfo,
    CompleteWord,
    BookmarksToggle,
    BookmarksNext,
    BookmarksPrevious,
    BookmarksClearAll,
    StepOut,
    FindPrevWordUnderCursor,
    FindNextWordUnderCursor,
    ObjBrwFindWholeWordOnly,
    ObjBrwShowHiddenMembers,
    ObjBrwViewDefinition,
    ObjBrwGroupMembers,
    SelectReport,
    Publish,
    SaveAsHTML,
    SaveAsIDC,
    SaveAsASP,
    PublishDefaults,
    EditHyperlink,
    OpenHyperlink,
    OpenNewHyperlink,
    CopyHyperlink,
    HyperlinkDisplayText,
    TabControlPageOrder,
    InsertPage,
    DeletePage,
    SelectAll,
    CreateMenuFromMacro,
    CreateToolbarFromMacro,
    CreateShortcutMenuFromMacro,
    Delete,
    RunOpenMacro,
    LastPosition,
    Print,
    FindNext,
    StepInto,
    ClearHyperlink,
    DataAccessPageBrowse,
    NewObjectDataAccessPage,
    SelectDataAccessPage,
    ViewDataAccessPages,
    NewObjectView,
    NewObjectStoredProcedure,
    NewObjectDiagram,
    ViewFieldList,
    ViewDiagrams,
    ViewStoredProcedures,
    ViewViews,
    ViewShowPaneSQL,
    ViewShowPaneDiagram,
    ViewShowPaneGrid,
    ViewVerifySQL,
    QueryGroupBy,
    QueryAddToOutput,
    ViewTableColumnNames,
    ViewTableNameOnly,
    HidePane,
    Remove,
    ViewTableColumnProperties,
    ViewTableKeys,
    ViewTableUserView,
    ZoomSelection,
    DiagramNewLabel,
    DiagramAddRelatedTables,
    DiagramShowRelationshipLabels,
    DiagramModifyUserDefinedView,
    DiagramViewPageBreaks,
    DiagramRecalculatePageBreaks,
    DiagramAutosizeSelectedTables,
    DiagramLayoutSelection,
    DiagramLayoutDiagram,
    DiagramNewTable,
    DiagramDeleteRelationship,
    Connection,
    EditTriggers,
    DataAccessPageDesignView,
    Promote,
    GroupByTable,
    Demote,
    SaveAsDataAccessPage,
    MicrosoftScriptEditor,
    WorkGroupAdministrator,
    NewObjectFunction,
    ViewFunctions,
    PivotTableView,
    PivotChartView,
    PivotAutoFilter,
    PivotTableSubtotal,
    PivotCollapse,
    PivotExpand,
    PivotTableHideDetails,
    PivotTableShowDetails,
    PivotRefresh,
    PivotTableExportToExcel,
    PivotTableMoveToRowArea,
    PivotTableMoveToColumnArea,
    PivotTableMoveToFilterArea,
    PivotTableMoveToDetailArea,
    PivotTablePromote,
    PivotTableDemote,
    PivotAutoSum,
    PivotAutoCount,
    PivotAutoMin,
    PivotAutoAverage,
    PivotAutoStdDev,
    PivotAutoVar,
    PivotAutoStdDevP,
    PivotAutoVarP,
    PivotShowTop1,
    PivotShowTop2,
    PivotShowTop5,
    PivotShowTop10,
    PivotShowTop25,
    PivotShowTop1Percent,
    PivotShowTop2Percent,
    PivotShowTop5Percent,
    PivotShowTop10Percent,
    PivotShowTop25Percent,
    PivotShowTopOther,
    PivotShowBottom1,
    PivotShowBottom2,
    PivotShowBottom5,
    PivotShowBottom10,
    PivotShowBottom25,
    PivotShowBottom1Percent,
    PivotShowBottom2Percent,
    PivotShowBottom5Percent,
    PivotShowBottom10Percent,
    PivotShowBottom25Percent,
    PivotShowBottomOther,
    PivotTableCreateCalcTotal,
    PivotTableCreateCalcField,
    PivotTableShowAsNormal,
    PivotTablePercentRowTotal,
    PivotTablePercentColumnTotal,
    PivotTablePercentParentRowItem,
    PivotTablePercentParentColumnItem,
    PivotTablePercentGrandTotal,
    PivotTableExpandIndicators,
    PivotDropAreas,
    PivotChartType,
    PivotDelete,
    PivotChartShowLegend,
    PivotChartByRowByColumn,
    PivotChartDrillInto,
    PivotMultiplePlots,
    PivotMultiplePlotsUnifiedScale,
    PivotChartUndo,
    PivotShowAll,
    SubformFormView,
    SubformDatasheetView,
    SubformPivotTableView,
    SubformPivotChartView,
    WebPagePreview,
    PageProperties,
    DataOutline,
    InsertMovieFromFile,
    InsertPivotTable,
    InsertSpreadsheet,
    InsertUnboundSection,
    WebTheme,
    BackgroundPicture,
    BackgroundSound,
    AlignMiddle,
    AlignCenter,
    AlignmentAndSizing,
    DataAccessPageFieldListRefresh,
    DataAccessPageAddToPage,
    Zoom500,
    Zoom1000,
    PrintRelationships,
    GroupControls,
    UngroupControls,
    WebPageProperties,
    Export,
    OfficeClipboard,
    DeleteTable,
    PasteAsHyperlink,
    NewGroup,
    RenameGroup,
    DeleteGroup,
    AddToNewGroup,
    SubformInNewWindow,
    ServerProperties,
    TableCustomView,
    TableAddTable,
    InsertSubdatasheet,
    ConditionalFormating,
    ChangeToCommandButton,
    SubdatasheetRemove,
    ServerFilterByForm,
    MaximumRecords,
    Speech,
    Backup,
    Restore,
    SubdatasheetCollapseAll,
    CopyDatabaseFile,
    DropSQLDatabase,
    LinkedTableManager,
    DatabaseSplitter,
    SwitchboardManager,
    UpsizingWizard,
    PartialReplicaWizard,
    VisualBasicEditor,
    AddInManager,
    PivotTableClearCustomOrdering,
    PivotTableFilterBySelection,
    PivotTableRemove,
    PivotTableGroupItems,
    PivotTableUngroupItems,
    PivotChartDrillOut,
    ShowEnvelope,
    PivotChartSortAscByTotal,
    PivotChartSortDescByTotal,
    ViewObjectDependencies,
    PublishDatabase,
    CloseDatabase,
    ReportView,
    ToggleOffline,
    RefreshData,
    ShareOnSharePoint,
    SavedImports,
    ImportAttachAccess,
    ImportAttachExcel,
    ImportAttachText,
    ImportAttachSharePointList,
    ImportAttachXML,
    ImportAttachODBC,
    ImportAttachHTML,
    ImportAttachOutlook,
    ImportAttachdBase,
    ImportAttachParadox,
    ImportAttachLotus,
    SavedExports,
    ExportExcel,
    ExportSharePointList,
    ExportRTF,
    ExportAccess,
    ExportText,
    ExportXML,
    ExportODBC,
    ExportSnapShot,
    ExportHTML,
    ExportdBase,
    ExportParadox,
    ExportLotus,
    StackedLayout,
    TabularLayout,
    SelectEntireRow,
    SelectEntireColumn,
    MoveColumnCellUp,
    MoveColumnCellDown,
    LayoutGridlinesBoth,
    LayoutGridlinesVertical,
    LayoutGridlinesHorizontal,
    LayoutGridlinesNone,
    LayoutGridlinesCrossHatch,
    LayoutGridlinesTop,
    LayoutGridlinesBottom,
    LayoutGridlinesOutline,
    RemoveFromLayout,
    AddFromOutlook,
    SaveAsOutlookContact,
    InsertLogo,
    InsertTitle,
    PasteFormatting,
    MacroArguments,
    MacroAllActions,
    PrintSelection,
    PublishFixedFormat,
    ExportFixedFormat,
    LayoutView,
    NewObjectContinuousForm,
    NewObjectSplitForm,
    NewObjectPivotChart,
    NewObjectPivotTable,
    NewObjectDatasheetForm,
    NewObjectModalForm,
    NewObjectBlankForm,
    NewObjectLabelsReport,
    NewObjectBlankReport,
    NewObjectDesignQuery,
    NewObjectDesignForm,
    NewObjectDesignReport,
    NewObjectDesignTable,
    EditListItems,
    ManageReplies,
    AnchorTopLeft,
    AnchorStretchAcross,
    AnchorTopRight,
    AnchorStretchDown,
    AnchorStretchDownAcross,
    AnchorStretchDownRight,
    AnchorBottomLeft,
    AnchorBottomStretchAcross,
    AnchorBottomRight,
    FilterMenu,
    ShowColumnHistory,
    BrowseSharePointList,
    ModifySharePointList,
    ModifySharePointListAlerts,
    ModifySharePointListWorkflow,
    ModifySharePointListPermissions,
    RefreshSharePointList,
    DeleteSharePointList,
    ControlMarginsNone,
    ControlMarginsNarrow,
    ControlMarginsMedium,
    ControlMarginsWide,
    ControlPaddingNone,
    ControlPaddingNarrow,
    ControlPaddingMedium,
    ControlPaddingWide,
    ShowDatePicker,
    SetCaption,
    Synchronize,
    DiscardChanges,
    DiscardChangesAndRefresh,
    SharePointSiteRecycleBin,
    ToggleCacheListData,
    RemoveFilterFromCurrentColumn,
    RemoveAllFilters,
    RemoveAllSorts,
    CloseAll,
    FieldTemplates,
    ApplyAutoFormat1,
    ApplyAutoFormat2,
    ApplyAutoFormat3,
    ApplyAutoFormat4,
    ApplyAutoFormat5,
    ApplyAutoFormat6,
    ApplyAutoFormat7,
    ApplyAutoFormat8,
    ApplyAutoFormat9,
    ApplyAutoFormat10,
    ApplyAutoFormat11,
    ApplyAutoFormat12,
    ApplyAutoFormat13,
    ApplyAutoFormat14,
    ApplyAutoFormat15,
    ApplyAutoFormat16,
    ApplyAutoFormat17,
    ApplyAutoFormat18,
    ApplyAutoFormat20,
    ApplyAutoFormat21,
    ApplyAutoFormat22,
    ApplyAutoFormat23,
    ApplyAutoFormat24,
    ApplyAutoFormat25,
    ManageAttachments,
    WorkflowTasks,
    StartNewWorkflow,
    ShowMessageBar,
    HideMessageBar,
    LayoutInsertRowAbove,
    LayoutInsertRowBelow,
    LayoutInsertColumnLeft,
    LayoutInsertColumnRight,
    LayoutMergeCells,
    LayoutSplitColumnCell,
    LayoutSplitRowCell,
    ShowLogicCatalog,
    SaveAsTemplate,
    SaveDatabaseAsNewTemplatePart,
    SaveSelectionAsNewDataType,
    NewObjectNavigationTop,
    NewObjectNavigationLeft,
    NewObjectNavigationRight,
    NewObjectNavigationTopTop,
    NewObjectNavigationTopLeft,
    NewObjectNavigationTopRight,
    CompatCheckDatabase,
    CompatCheckCurrentObject,
    DesignObject,
    CalculatedColumn,
    SyncWebApplication,
    ConvertLinkedTableToLocal,
    NewObjectContinuousFormWeb,
    NewObjectDatasheetFormWeb,
    NewObjectBlankFormWeb,
    NewObjectBlankReportWeb,
    NewObjectAutoFormWeb,
    NewObjectAutoReportWeb,
    NewObjectQueryWeb,
    NewObjectMacroWeb,
    NewObjectNavigationTopWeb,
    NewObjectNavigationLeftWeb,
    NewObjectNavigationRightWeb,
    NewObjectNavigationTopTopWeb,
    NewObjectNavigationTopLeftWeb,
    NewObjectNavigationTopRightWeb,
    SelectEntireLayout,
    PrepareDatabaseForWeb,
    ManageTableEvents,
    AddDataMacroAfterInsert,
    AddDataMacroAfterDelete,
    AddDataMacroValidateDelete,
    AddDataMacroValidateChange,
    AddNamedDataMacro,
    InsertNavigationButton,
    Unknown(u16),
}

impl From<u16> for AcCmd {
    fn from(n: u16) -> AcCmd {
        match n {
            1 => AcCmd::WindowUnhide,
            2 => AcCmd::WindowHide,
            3 => AcCmd::Exit,
            4 => AcCmd::CompactDatabase,
            5 => AcCmd::EncryptDecryptDatabase,
            6 => AcCmd::RepairDatabase,
            7 => AcCmd::MakeMDEFile,
            8 => AcCmd::MoreWindows,
            9 => AcCmd::AppRestore,
            10 => AcCmd::AppMaximize,
            11 => AcCmd::AppMinimize,
            12 => AcCmd::AppMove,
            13 => AcCmd::AppSize,
            14 => AcCmd::DocRestore,
            15 => AcCmd::DocMaximize,
            16 => AcCmd::DocMove,
            17 => AcCmd::DocSize,
            18 => AcCmd::Refresh,
            19 => AcCmd::Font,
            20 => AcCmd::Save,
            21 => AcCmd::SaveAs,
            22 => AcCmd::WindowCascade,
            23 => AcCmd::TileVertically,
            24 => AcCmd::WindowArrangeIcons,
            25 => AcCmd::OpenDatabase,
            26 => AcCmd::NewDatabase,
            27 => AcCmd::OLEDDELinks,
            28 => AcCmd::RecordsGoToNew,
            29 => AcCmd::Replace,
            30 => AcCmd::Find,
            31 => AcCmd::RunMacro,
            32 => AcCmd::PageSetup,
            33 => AcCmd::InsertObject,
            34 => AcCmd::Duplicate,
            35 => AcCmd::AboutMicrosoftAccess,
            36 => AcCmd::FormHdrFtr,
            37 => AcCmd::ReportHdrFtr,
            38 => AcCmd::PasteAppend,
            39 => AcCmd::InsertFile,
            40 => AcCmd::SelectForm,
            41 => AcCmd::TabOrder,
            42 => AcCmd::FieldList,
            43 => AcCmd::AlignLeft,
            44 => AcCmd::AlignRight,
            45 => AcCmd::AlignTop,
            46 => AcCmd::AlignBottom,
            47 => AcCmd::AlignToGrid,
            48 => AcCmd::SizeToGrid,
            49 => AcCmd::Options,
            50 => AcCmd::SelectRecord,
            51 => AcCmd::SortingAndGrouping,
            52 => AcCmd::BringToFront,
            53 => AcCmd::SendToBack,
            54 => AcCmd::PrintPreview,
            55 => AcCmd::ApplyDefault,
            56 => AcCmd::SetControlDefaults,
            57 => AcCmd::OLEObjectDefaultVerb,
            58 => AcCmd::Close,
            59 => AcCmd::SizeToFit,
            60 => AcCmd::DocMinimize,
            61 => AcCmd::ViewRuler,
            62 => AcCmd::SnapToGrid,
            63 => AcCmd::ViewGrid,
            64 => AcCmd::PasteSpecial,
            65 => AcCmd::RecordsGoToNext,
            66 => AcCmd::RecordsGoToPrevious,
            67 => AcCmd::RecordsGoToFirst,
            68 => AcCmd::RecordsGoToLast,
            69 => AcCmd::SizeToFitForm,
            70 => AcCmd::EditingAllowed,
            71 => AcCmd::ClearGrid,
            72 => AcCmd::JoinProperties,
            73 => AcCmd::QueryTotals,
            74 => AcCmd::QueryTypeCrosstab,
            75 => AcCmd::TableNames,
            76 => AcCmd::QueryParameters,
            77 => AcCmd::FormatCells,
            78 => AcCmd::DataEntry,
            79 => AcCmd::HideColumns,
            80 => AcCmd::UnhideColumns,
            81 => AcCmd::DeleteQueryColumn,
            82 => AcCmd::InsertQueryColumn,
            84 => AcCmd::RemoveTable,
            85 => AcCmd::ViewToolbox,
            86 => AcCmd::MacroNames,
            87 => AcCmd::MacroConditions,
            88 => AcCmd::SingleStep,
            89 => AcCmd::QueryTypeSelect,
            90 => AcCmd::QueryTypeUpdate,
            91 => AcCmd::QueryTypeAppend,
            92 => AcCmd::QueryTypeDelete,
            93 => AcCmd::ApplyFilterSort,
            94 => AcCmd::QueryTypeMakeTable,
            95 => AcCmd::LoadFromQuery,
            96 => AcCmd::SaveAsQuery,
            97 => AcCmd::SaveRecord,
            99 => AcCmd::AdvancedFilterSort,
            100 => AcCmd::MicrosoftAccessHelpTopics,
            102 => AcCmd::LinkTables,
            103 => AcCmd::UserAndGroupPermissions,
            104 => AcCmd::UserAndGroupAccounts,
            105 => AcCmd::FreezeColumn,
            106 => AcCmd::UnfreezeAllColumns,
            107 => AcCmd::PrimaryKey,
            108 => AcCmd::SubformDatasheet,
            109 => AcCmd::SelectAllRecords,
            110 => AcCmd::ViewTables,
            111 => AcCmd::ViewQueries,
            112 => AcCmd::ViewForms,
            113 => AcCmd::ViewReports,
            114 => AcCmd::ViewMacros,
            115 => AcCmd::ViewModules,
            116 => AcCmd::RowHeight,
            117 => AcCmd::ColumnWidth,
            118 => AcCmd::InsertFileIntoModule,
            119 => AcCmd::SaveModuleAsText,
            120 => AcCmd::FindPrevious,
            121 => AcCmd::WindowSplit,
            122 => AcCmd::ProcedureDefinition,
            123 => AcCmd::DebugWindow,
            124 => AcCmd::Reset,
            125 => AcCmd::CompileAllModules,
            126 => AcCmd::CompileAndSaveAllModules,
            127 => AcCmd::GoContinue,
            128 => AcCmd::StepOver,
            129 => AcCmd::SetNextStatement,
            130 => AcCmd::ShowNextStatement,
            131 => AcCmd::ToggleBreakpoint,
            132 => AcCmd::ClearAllBreakpoints,
            133 => AcCmd::Relationships,
            134 => AcCmd::NewObjectTable,
            135 => AcCmd::NewObjectQuery,
            136 => AcCmd::NewObjectForm,
            137 => AcCmd::NewObjectReport,
            138 => AcCmd::NewObjectMacro,
            139 => AcCmd::NewObjectModule,
            140 => AcCmd::NewObjectClassModule,
            141 => AcCmd::LayoutPreview,
            142 => AcCmd::SaveAsReport,
            143 => AcCmd::Rename,
            144 => AcCmd::RemoveFilterSort,
            145 => AcCmd::SaveLayout,
            146 => AcCmd::ClearAll,
            147 => AcCmd::HideTable,
            148 => AcCmd::ShowDirectRelationships,
            149 => AcCmd::ShowAllRelationships,
            150 => AcCmd::CreateRelationship,
            151 => AcCmd::EditRelationship,
            152 => AcCmd::Indexes,
            153 => AcCmd::AlignToShortest,
            154 => AcCmd::AlignToTallest,
            155 => AcCmd::SizeToNarrowest,
            156 => AcCmd::SizeToWidest,
            157 => AcCmd::HorizontalSpacingMakeEqual,
            158 => AcCmd::HorizontalSpacingDecrease,
            159 => AcCmd::HorizontalSpacingIncrease,
            160 => AcCmd::VerticalSpacingMakeEqual,
            161 => AcCmd::VerticalSpacingDecrease,
            162 => AcCmd::VerticalSpacingIncrease,
            163 => AcCmd::SortAscending,
            164 => AcCmd::SortDescending,
            165 => AcCmd::ToolbarsCustomize,
            167 => AcCmd::OLEObjectConvert,
            168 => AcCmd::QueryTypeSQLDataDefinition,
            169 => AcCmd::QueryTypeSQLPassThrough,
            170 => AcCmd::ViewCode,
            171 => AcCmd::ConvertDatabase,
            172 => AcCmd::CallStack,
            173 => AcCmd::Send,
            175 => AcCmd::OutputToExcel,
            176 => AcCmd::OutputToRTF,
            177 => AcCmd::OutputToText,
            178 => AcCmd::InvokeBuilder,
            179 => AcCmd::ZoomBox,
            180 => AcCmd::QueryTypeSQLUnion,
            181 => AcCmd::Run,
            182 => AcCmd::PageHdrFtr,
            183 => AcCmd::DesignView,
            184 => AcCmd::SQLView,
            185 => AcCmd::ShowTable,
            186 => AcCmd::CloseWindow,
            187 => AcCmd::InsertRows,
            188 => AcCmd::DeleteRows,
            189 => AcCmd::Cut,
            190 => AcCmd::Copy,
            191 => AcCmd::Paste,
            192 => AcCmd::AutoDial,
            193 => AcCmd::NewObjectAutoForm,
            194 => AcCmd::NewObjectAutoReport,
            195 => AcCmd::WordMailMerge,
            196 => AcCmd::TestValidationRules,
            197 => AcCmd::ControlWizardsToggle,
            198 => AcCmd::End,
            199 => AcCmd::Redo,
            200 => AcCmd::ObjectBrowser,
            201 => AcCmd::AddWatch,
            202 => AcCmd::EditWatch,
            203 => AcCmd::QuickWatch,
            204 => AcCmd::StepToCursor,
            205 => AcCmd::Indent,
            206 => AcCmd::Outdent,
            207 => AcCmd::FilterByForm,
            208 => AcCmd::FilterBySelection,
            209 => AcCmd::ViewLargeIcons,
            210 => AcCmd::ViewDetails,
            211 => AcCmd::ViewSmallIcons,
            212 => AcCmd::ViewList,
            213 => AcCmd::LineUpIcons,
            214 => AcCmd::ArrangeIconsByName,
            215 => AcCmd::ArrangeIconsByType,
            216 => AcCmd::ArrangeIconsByCreated,
            217 => AcCmd::ArrangeIconsByModified,
            218 => AcCmd::ArrangeIconsAuto,
            219 => AcCmd::CreateShortcut,
            220 => AcCmd::ToggleFilter,
            221 => AcCmd::OpenTable,
            222 => AcCmd::InsertPicture,
            223 => AcCmd::DeleteRecord,
            224 => AcCmd::StartupProperties,
            225 => AcCmd::PageNumber,
            226 => AcCmd::DateAndTime,
            227 => AcCmd::ChangeToTextBox,
            228 => AcCmd::ChangeToLabel,
            229 => AcCmd::ChangeToListBox,
            230 => AcCmd::ChangeToComboBox,
            231 => AcCmd::ChangeToCheckBox,
            232 => AcCmd::ChangeToToggleButton,
            233 => AcCmd::ChangeToOptionButton,
            234 => AcCmd::ChangeToImage,
            235 => AcCmd::AnswerWizard,
            236 => AcCmd::MicrosoftOnTheWeb,
            237 => AcCmd::ClearItemDefaults,
            238 => AcCmd::Zoom200,
            239 => AcCmd::Zoom150,
            240 => AcCmd::Zoom100,
            241 => AcCmd::Zoom75,
            242 => AcCmd::Zoom50,
            243 => AcCmd::Zoom25,
            244 => AcCmd::Zoom10,
            245 => AcCmd::FitToWindow,
            246 => AcCmd::PreviewOnePage,
            247 => AcCmd::PreviewTwoPages,
            248 => AcCmd::PreviewFourPages,
            249 => AcCmd::PreviewEightPages,
            250 => AcCmd::PreviewTwelvePages,
            251 => AcCmd::OpenURL,
            252 => AcCmd::OpenStartPage,
            253 => AcCmd::OpenSearchPage,
            254 => AcCmd::RegisterActiveXControls,
            255 => AcCmd::DeleteTab,
            256 => AcCmd::DatabaseProperties,
            257 => AcCmd::Import,
            258 => AcCmd::InsertActiveXControl,
            259 => AcCmd::InsertHyperlink,
            260 => AcCmd::References,
            261 => AcCmd::AutoCorrect,
            262 => AcCmd::InsertProcedure,
            263 => AcCmd::CreateReplica,
            264 => AcCmd::SynchronizeNow,
            265 => AcCmd::RecoverDesignMaster,
            266 => AcCmd::ResolveConflicts,
            267 => AcCmd::DeleteWatch,
            269 => AcCmd::Spelling,
            270 => AcCmd::AutoFormat,
            271 => AcCmd::DeleteTableColumn,
            272 => AcCmd::InsertTableColumn,
            273 => AcCmd::InsertLookupColumn,
            274 => AcCmd::RenameColumn,
            275 => AcCmd::SetDatabasePassword,
            276 => AcCmd::UserLevelSecurityWizard,
            277 => AcCmd::FilterExcludingSelection,
            278 => AcCmd::QuickPrint,
            279 => AcCmd::ConvertMacrosToVisualBasic,
            280 => AcCmd::SaveAllModules,
            281 => AcCmd::FormView,
            282 => AcCmd::DatasheetView,
            283 => AcCmd::AnalyzePerformance,
            284 => AcCmd::AnalyzeTable,
            285 => AcCmd::Documenter,
            286 => AcCmd::TileHorizontally,
            287 => AcCmd::Properties,
            288 => AcCmd::TransparentBackground,
            289 => AcCmd::TransparentBorder,
            290 => AcCmd::CompileLoadedModules,
            291 => AcCmd::InsertLookupField,
            292 => AcCmd::Undo,
            293 => AcCmd::InsertChart,
            294 => AcCmd::GoBack,
            295 => AcCmd::GoForward,
            296 => AcCmd::StopLoadingPage,
            297 => AcCmd::RefreshPage,
            298 => AcCmd::FavoritesOpen,
            299 => AcCmd::FavoritesAddTo,
            300 => AcCmd::ShowOnlyWebToolbar,
            301 => AcCmd::ToolbarControlProperties,
            302 => AcCmd::ShowMembers,
            303 => AcCmd::ListConstants,
            304 => AcCmd::QuickInfo,
            305 => AcCmd::ParameterInfo,
            306 => AcCmd::CompleteWord,
            307 => AcCmd::BookmarksToggle,
            308 => AcCmd::BookmarksNext,
            309 => AcCmd::BookmarksPrevious,
            310 => AcCmd::BookmarksClearAll,
            311 => AcCmd::StepOut,
            312 => AcCmd::FindPrevWordUnderCursor,
            313 => AcCmd::FindNextWordUnderCursor,
            314 => AcCmd::ObjBrwFindWholeWordOnly,
            315 => AcCmd::ObjBrwShowHiddenMembers,
            317 => AcCmd::ObjBrwViewDefinition,
            318 => AcCmd::ObjBrwGroupMembers,
            319 => AcCmd::SelectReport,
            320 => AcCmd::Publish,
            321 => AcCmd::SaveAsHTML,
            322 => AcCmd::SaveAsIDC,
            323 => AcCmd::SaveAsASP,
            324 => AcCmd::PublishDefaults,
            325 => AcCmd::EditHyperlink,
            326 => AcCmd::OpenHyperlink,
            327 => AcCmd::OpenNewHyperlink,
            328 => AcCmd::CopyHyperlink,
            329 => AcCmd::HyperlinkDisplayText,
            330 => AcCmd::TabControlPageOrder,
            331 => AcCmd::InsertPage,
            332 => AcCmd::DeletePage,
            333 => AcCmd::SelectAll,
            334 => AcCmd::CreateMenuFromMacro,
            335 => AcCmd::CreateToolbarFromMacro,
            336 => AcCmd::CreateShortcutMenuFromMacro,
            337 => AcCmd::Delete,
            338 => AcCmd::RunOpenMacro,
            339 => AcCmd::LastPosition,
            340 => AcCmd::Print,
            341 => AcCmd::FindNext,
            342 => AcCmd::StepInto,
            343 => AcCmd::ClearHyperlink,
            344 => AcCmd::DataAccessPageBrowse,
            346 => AcCmd::NewObjectDataAccessPage,
            347 => AcCmd::SelectDataAccessPage,
            349 => AcCmd::ViewDataAccessPages,
            350 => AcCmd::NewObjectView,
            351 => AcCmd::NewObjectStoredProcedure,
            352 => AcCmd::NewObjectDiagram,
            353 => AcCmd::ViewFieldList,
            354 => AcCmd::ViewDiagrams,
            355 => AcCmd::ViewStoredProcedures,
            356 => AcCmd::ViewViews,
            357 => AcCmd::ViewShowPaneSQL,
            358 => AcCmd::ViewShowPaneDiagram,
            359 => AcCmd::ViewShowPaneGrid,
            360 => AcCmd::ViewVerifySQL,
            361 => AcCmd::QueryGroupBy,
            362 => AcCmd::QueryAddToOutput,
            363 => AcCmd::ViewTableColumnNames,
            364 => AcCmd::ViewTableNameOnly,
            365 => AcCmd::HidePane,
            366 => AcCmd::Remove,
            368 => AcCmd::ViewTableColumnProperties,
            369 => AcCmd::ViewTableKeys,
            370 => AcCmd::ViewTableUserView,
            371 => AcCmd::ZoomSelection,
            372 => AcCmd::DiagramNewLabel,
            373 => AcCmd::DiagramAddRelatedTables,
            374 => AcCmd::DiagramShowRelationshipLabels,
            375 => AcCmd::DiagramModifyUserDefinedView,
            376 => AcCmd::DiagramViewPageBreaks,
            377 => AcCmd::DiagramRecalculatePageBreaks,
            378 => AcCmd::DiagramAutosizeSelectedTables,
            379 => AcCmd::DiagramLayoutSelection,
            380 => AcCmd::DiagramLayoutDiagram,
            381 => AcCmd::DiagramNewTable,
            382 => AcCmd::DiagramDeleteRelationship,
            383 => AcCmd::Connection,
            384 => AcCmd::EditTriggers,
            385 => AcCmd::DataAccessPageDesignView,
            386 => AcCmd::Promote,
            387 => AcCmd::GroupByTable,
            388 => AcCmd::Demote,
            389 => AcCmd::SaveAsDataAccessPage,
            390 => AcCmd::MicrosoftScriptEditor,
            391 => AcCmd::WorkGroupAdministrator,
            394 => AcCmd::NewObjectFunction,
            395 => AcCmd::ViewFunctions,
            396 => AcCmd::PivotTableView,
            397 => AcCmd::PivotChartView,
            398 => AcCmd::PivotAutoFilter,
            399 => AcCmd::PivotTableSubtotal,
            400 => AcCmd::PivotCollapse,
            401 => AcCmd::PivotExpand,
            402 => AcCmd::PivotTableHideDetails,
            403 => AcCmd::PivotTableShowDetails,
            404 => AcCmd::PivotRefresh,
            405 => AcCmd::PivotTableExportToExcel,
            406 => AcCmd::PivotTableMoveToRowArea,
            407 => AcCmd::PivotTableMoveToColumnArea,
            408 => AcCmd::PivotTableMoveToFilterArea,
            409 => AcCmd::PivotTableMoveToDetailArea,
            410 => AcCmd::PivotTablePromote,
            411 => AcCmd::PivotTableDemote,
            412 => AcCmd::PivotAutoSum,
            413 => AcCmd::PivotAutoCount,
            414 => AcCmd::PivotAutoMin,
            416 => AcCmd::PivotAutoAverage,
            417 => AcCmd::PivotAutoStdDev,
            418 => AcCmd::PivotAutoVar,
            419 => AcCmd::PivotAutoStdDevP,
            420 => AcCmd::PivotAutoVarP,
            421 => AcCmd::PivotShowTop1,
            422 => AcCmd::PivotShowTop2,
            423 => AcCmd::PivotShowTop5,
            424 => AcCmd::PivotShowTop10,
            425 => AcCmd::PivotShowTop25,
            426 => AcCmd::PivotShowTop1Percent,
            427 => AcCmd::PivotShowTop2Percent,
            428 => AcCmd::PivotShowTop5Percent,
            429 => AcCmd::PivotShowTop10Percent,
            430 => AcCmd::PivotShowTop25Percent,
            431 => AcCmd::PivotShowTopOther,
            432 => AcCmd::PivotShowBottom1,
            433 => AcCmd::PivotShowBottom2,
            434 => AcCmd::PivotShowBottom5,
            435 => AcCmd::PivotShowBottom10,
            436 => AcCmd::PivotShowBottom25,
            437 => AcCmd::PivotShowBottom1Percent,
            438 => AcCmd::PivotShowBottom2Percent,
            439 => AcCmd::PivotShowBottom5Percent,
            440 => AcCmd::PivotShowBottom10Percent,
            441 => AcCmd::PivotShowBottom25Percent,
            442 => AcCmd::PivotShowBottomOther,
            443 => AcCmd::PivotTableCreateCalcTotal,
            444 => AcCmd::PivotTableCreateCalcField,
            445 => AcCmd::PivotTableShowAsNormal,
            446 => AcCmd::PivotTablePercentRowTotal,
            447 => AcCmd::PivotTablePercentColumnTotal,
            448 => AcCmd::PivotTablePercentParentRowItem,
            449 => AcCmd::PivotTablePercentParentColumnItem,
            450 => AcCmd::PivotTablePercentGrandTotal,
            451 => AcCmd::PivotTableExpandIndicators,
            452 => AcCmd::PivotDropAreas,
            453 => AcCmd::PivotChartType,
            454 => AcCmd::PivotDelete,
            455 => AcCmd::PivotChartShowLegend,
            456 => AcCmd::PivotChartByRowByColumn,
            457 => AcCmd::PivotChartDrillInto,
            458 => AcCmd::PivotMultiplePlots,
            459 => AcCmd::PivotMultiplePlotsUnifiedScale,
            460 => AcCmd::PivotChartUndo,
            461 => AcCmd::PivotShowAll,
            462 => AcCmd::SubformFormView,
            463 => AcCmd::SubformDatasheetView,
            464 => AcCmd::SubformPivotTableView,
            465 => AcCmd::SubformPivotChartView,
            466 => AcCmd::WebPagePreview,
            467 => AcCmd::PageProperties,
            468 => AcCmd::DataOutline,
            469 => AcCmd::InsertMovieFromFile,
            470 => AcCmd::InsertPivotTable,
            471 => AcCmd::InsertSpreadsheet,
            472 => AcCmd::InsertUnboundSection,
            473 => AcCmd::WebTheme,
            474 => AcCmd::BackgroundPicture,
            475 => AcCmd::BackgroundSound,
            476 => AcCmd::AlignMiddle,
            477 => AcCmd::AlignCenter,
            478 => AcCmd::AlignmentAndSizing,
            479 => AcCmd::DataAccessPageFieldListRefresh,
            480 => AcCmd::DataAccessPageAddToPage,
            481 => AcCmd::Zoom500,
            482 => AcCmd::Zoom1000,
            483 => AcCmd::PrintRelationships,
            484 => AcCmd::GroupControls,
            485 => AcCmd::UngroupControls,
            486 => AcCmd::WebPageProperties,
            487 => AcCmd::Export,
            488 => AcCmd::OfficeClipboard,
            489 => AcCmd::DeleteTable,
            490 => AcCmd::PasteAsHyperlink,
            491 => AcCmd::NewGroup,
            492 => AcCmd::RenameGroup,
            493 => AcCmd::DeleteGroup,
            494 => AcCmd::AddToNewGroup,
            495 => AcCmd::SubformInNewWindow,
            496 => AcCmd::ServerProperties,
            497 => AcCmd::TableCustomView,
            498 => AcCmd::TableAddTable,
            499 => AcCmd::InsertSubdatasheet,
            500 => AcCmd::ConditionalFormating,
            501 => AcCmd::ChangeToCommandButton,
            506 => AcCmd::SubdatasheetRemove,
            507 => AcCmd::ServerFilterByForm,
            508 => AcCmd::MaximumRecords,
            511 => AcCmd::Speech,
            513 => AcCmd::Backup,
            514 => AcCmd::Restore,
            515 => AcCmd::SubdatasheetCollapseAll,
            516 => AcCmd::CopyDatabaseFile,
            517 => AcCmd::DropSQLDatabase,
            519 => AcCmd::LinkedTableManager,
            520 => AcCmd::DatabaseSplitter,
            521 => AcCmd::SwitchboardManager,
            522 => AcCmd::UpsizingWizard,
            524 => AcCmd::PartialReplicaWizard,
            525 => AcCmd::VisualBasicEditor,
            526 => AcCmd::AddInManager,
            527 => AcCmd::PivotTableClearCustomOrdering,
            528 => AcCmd::PivotTableFilterBySelection,
            529 => AcCmd::PivotTableRemove,
            530 => AcCmd::PivotTableGroupItems,
            531 => AcCmd::PivotTableUngroupItems,
            532 => AcCmd::PivotChartDrillOut,
            533 => AcCmd::ShowEnvelope,
            534 => AcCmd::PivotChartSortAscByTotal,
            535 => AcCmd::PivotChartSortDescByTotal,
            536 => AcCmd::ViewObjectDependencies,
            537 => AcCmd::PublishDatabase,
            538 => AcCmd::CloseDatabase,
            539 => AcCmd::ReportView,
            540 => AcCmd::ToggleOffline,
            541 => AcCmd::RefreshData,
            542 => AcCmd::ShareOnSharePoint,
            543 => AcCmd::SavedImports,
            544 => AcCmd::ImportAttachAccess,
            545 => AcCmd::ImportAttachExcel,
            546 => AcCmd::ImportAttachText,
            547 => AcCmd::ImportAttachSharePointList,
            548 => AcCmd::ImportAttachXML,
            549 => AcCmd::ImportAttachODBC,
            550 => AcCmd::ImportAttachHTML,
            551 => AcCmd::ImportAttachOutlook,
            552 => AcCmd::ImportAttachdBase,
            553 => AcCmd::ImportAttachParadox,
            554 => AcCmd::ImportAttachLotus,
            555 => AcCmd::SavedExports,
            556 => AcCmd::ExportExcel,
            557 => AcCmd::ExportSharePointList,
            558 => AcCmd::ExportRTF,
            559 => AcCmd::ExportAccess,
            560 => AcCmd::ExportText,
            561 => AcCmd::ExportXML,
            562 => AcCmd::ExportODBC,
            563 => AcCmd::ExportSnapShot,
            564 => AcCmd::ExportHTML,
            565 => AcCmd::ExportdBase,
            566 => AcCmd::ExportParadox,
            567 => AcCmd::ExportLotus,
            568 => AcCmd::StackedLayout,
            569 => AcCmd::TabularLayout,
            570 => AcCmd::SelectEntireRow,
            571 => AcCmd::SelectEntireColumn,
            572 => AcCmd::MoveColumnCellUp,
            573 => AcCmd::MoveColumnCellDown,
            574 => AcCmd::LayoutGridlinesBoth,
            575 => AcCmd::LayoutGridlinesVertical,
            576 => AcCmd::LayoutGridlinesHorizontal,
            577 => AcCmd::LayoutGridlinesNone,
            578 => AcCmd::LayoutGridlinesCrossHatch,
            579 => AcCmd::LayoutGridlinesTop,
            580 => AcCmd::LayoutGridlinesBottom,
            581 => AcCmd::LayoutGridlinesOutline,
            582 => AcCmd::RemoveFromLayout,
            583 => AcCmd::AddFromOutlook,
            584 => AcCmd::SaveAsOutlookContact,
            585 => AcCmd::InsertLogo,
            586 => AcCmd::InsertTitle,
            587 => AcCmd::PasteFormatting,
            588 => AcCmd::MacroArguments,
            589 => AcCmd::MacroAllActions,
            590 => AcCmd::PrintSelection,
            591 => AcCmd::PublishFixedFormat,
            592 => AcCmd::ExportFixedFormat,
            593 => AcCmd::LayoutView,
            594 => AcCmd::NewObjectContinuousForm,
            595 => AcCmd::NewObjectSplitForm,
            596 => AcCmd::NewObjectPivotChart,
            597 => AcCmd::NewObjectPivotTable,
            598 => AcCmd::NewObjectDatasheetForm,
            599 => AcCmd::NewObjectModalForm,
            600 => AcCmd::NewObjectBlankForm,
            601 => AcCmd::NewObjectLabelsReport,
            602 => AcCmd::NewObjectBlankReport,
            603 => AcCmd::NewObjectDesignQuery,
            604 => AcCmd::NewObjectDesignForm,
            605 => AcCmd::NewObjectDesignReport,
            606 => AcCmd::NewObjectDesignTable,
            607 => AcCmd::EditListItems,
            609 => AcCmd::ManageReplies,
            610 => AcCmd::AnchorTopLeft,
            611 => AcCmd::AnchorStretchAcross,
            612 => AcCmd::AnchorTopRight,
            613 => AcCmd::AnchorStretchDown,
            614 => AcCmd::AnchorStretchDownAcross,
            615 => AcCmd::AnchorStretchDownRight,
            616 => AcCmd::AnchorBottomLeft,
            617 => AcCmd::AnchorBottomStretchAcross,
            618 => AcCmd::AnchorBottomRight,
            619 => AcCmd::FilterMenu,
            620 => AcCmd::ShowColumnHistory,
            621 => AcCmd::BrowseSharePointList,
            622 => AcCmd::ModifySharePointList,
            623 => AcCmd::ModifySharePointListAlerts,
            624 => AcCmd::ModifySharePointListWorkflow,
            625 => AcCmd::ModifySharePointListPermissions,
            626 => AcCmd::RefreshSharePointList,
            627 => AcCmd::DeleteSharePointList,
            628 => AcCmd::ControlMarginsNone,
            629 => AcCmd::ControlMarginsNarrow,
            630 => AcCmd::ControlMarginsMedium,
            631 => AcCmd::ControlMarginsWide,
            632 => AcCmd::ControlPaddingNone,
            633 => AcCmd::ControlPaddingNarrow,
            634 => AcCmd::ControlPaddingMedium,
            635 => AcCmd::ControlPaddingWide,
            636 => AcCmd::ShowDatePicker,
            637 => AcCmd::SetCaption,
            638 => AcCmd::Synchronize,
            639 => AcCmd::DiscardChanges,
            640 => AcCmd::DiscardChangesAndRefresh,
            641 => AcCmd::SharePointSiteRecycleBin,
            642 => AcCmd::ToggleCacheListData,
            643 => AcCmd::RemoveFilterFromCurrentColumn,
            644 => AcCmd::RemoveAllFilters,
            645 => AcCmd::RemoveAllSorts,
            646 => AcCmd::CloseAll,
            647 => AcCmd::FieldTemplates,
            648 => AcCmd::ApplyAutoFormat1,
            649 => AcCmd::ApplyAutoFormat2,
            650 => AcCmd::ApplyAutoFormat3,
            651 => AcCmd::ApplyAutoFormat4,
            652 => AcCmd::ApplyAutoFormat5,
            653 => AcCmd::ApplyAutoFormat6,
            654 => AcCmd::ApplyAutoFormat7,
            655 => AcCmd::ApplyAutoFormat8,
            656 => AcCmd::ApplyAutoFormat9,
            657 => AcCmd::ApplyAutoFormat10,
            658 => AcCmd::ApplyAutoFormat11,
            659 => AcCmd::ApplyAutoFormat12,
            660 => AcCmd::ApplyAutoFormat13,
            661 => AcCmd::ApplyAutoFormat14,
            662 => AcCmd::ApplyAutoFormat15,
            663 => AcCmd::ApplyAutoFormat16,
            664 => AcCmd::ApplyAutoFormat17,
            665 => AcCmd::ApplyAutoFormat18,
            667 => AcCmd::ApplyAutoFormat20,
            668 => AcCmd::ApplyAutoFormat21,
            669 => AcCmd::ApplyAutoFormat22,
            670 => AcCmd::ApplyAutoFormat23,
            671 => AcCmd::ApplyAutoFormat24,
            672 => AcCmd::ApplyAutoFormat25,
            673 => AcCmd::ManageAttachments,
            674 => AcCmd::WorkflowTasks,
            675 => AcCmd::StartNewWorkflow,
            676 => AcCmd::ShowMessageBar,
            677 => AcCmd::HideMessageBar,
            678 => AcCmd::LayoutInsertRowAbove,
            679 => AcCmd::LayoutInsertRowBelow,
            680 => AcCmd::LayoutInsertColumnLeft,
            681 => AcCmd::LayoutInsertColumnRight,
            682 => AcCmd::LayoutMergeCells,
            683 => AcCmd::LayoutSplitColumnCell,
            684 => AcCmd::LayoutSplitRowCell,
            685 => AcCmd::ShowLogicCatalog,
            686 => AcCmd::SaveAsTemplate,
            687 => AcCmd::SaveDatabaseAsNewTemplatePart,
            688 => AcCmd::SaveSelectionAsNewDataType,
            689 => AcCmd::NewObjectNavigationTop,
            690 => AcCmd::NewObjectNavigationLeft,
            691 => AcCmd::NewObjectNavigationRight,
            692 => AcCmd::NewObjectNavigationTopTop,
            693 => AcCmd::NewObjectNavigationTopLeft,
            694 => AcCmd::NewObjectNavigationTopRight,
            695 => AcCmd::CompatCheckDatabase,
            696 => AcCmd::CompatCheckCurrentObject,
            697 => AcCmd::DesignObject,
            698 => AcCmd::CalculatedColumn,
            699 => AcCmd::SyncWebApplication,
            700 => AcCmd::ConvertLinkedTableToLocal,
            701 => AcCmd::NewObjectContinuousFormWeb,
            702 => AcCmd::NewObjectDatasheetFormWeb,
            703 => AcCmd::NewObjectBlankFormWeb,
            704 => AcCmd::NewObjectBlankReportWeb,
            705 => AcCmd::NewObjectAutoFormWeb,
            706 => AcCmd::NewObjectAutoReportWeb,
            707 => AcCmd::NewObjectQueryWeb,
            708 => AcCmd::NewObjectMacroWeb,
            709 => AcCmd::NewObjectNavigationTopWeb,
            710 => AcCmd::NewObjectNavigationLeftWeb,
            711 => AcCmd::NewObjectNavigationRightWeb,
            712 => AcCmd::NewObjectNavigationTopTopWeb,
            713 => AcCmd::NewObjectNavigationTopLeftWeb,
            714 => AcCmd::NewObjectNavigationTopRightWeb,
            715 => AcCmd::SelectEntireLayout,
            716 => AcCmd::PrepareDatabaseForWeb,
            717 => AcCmd::ManageTableEvents,
            718 => AcCmd::AddDataMacroAfterInsert,
            720 => AcCmd::AddDataMacroAfterDelete,
            721 => AcCmd::AddDataMacroValidateDelete,
            722 => AcCmd::AddDataMacroValidateChange,
            723 => AcCmd::AddNamedDataMacro,
            724 => AcCmd::InsertNavigationButton,
            other => AcCmd::Unknown(other),
        }
    }
}

impl AcCmd {
    pub fn code(self) -> u16 {
        match self {
            AcCmd::WindowUnhide => 1,
            AcCmd::WindowHide => 2,
            AcCmd::Exit => 3,
            AcCmd::CompactDatabase => 4,
            AcCmd::EncryptDecryptDatabase => 5,
            AcCmd::RepairDatabase => 6,
            AcCmd::MakeMDEFile => 7,
            AcCmd::MoreWindows => 8,
            AcCmd::AppRestore => 9,
            AcCmd::AppMaximize => 10,
            AcCmd::AppMinimize => 11,
            AcCmd::AppMove => 12,
            AcCmd::AppSize => 13,
            AcCmd::DocRestore => 14,
            AcCmd::DocMaximize => 15,
            AcCmd::DocMove => 16,
            AcCmd::DocSize => 17,
            AcCmd::Refresh => 18,
            AcCmd::Font => 19,
            AcCmd::Save => 20,
            AcCmd::SaveAs => 21,
            AcCmd::WindowCascade => 22,
            AcCmd::TileVertically => 23,
            AcCmd::WindowArrangeIcons => 24,
            AcCmd::OpenDatabase => 25,
            AcCmd::NewDatabase => 26,
            AcCmd::OLEDDELinks => 27,
            AcCmd::RecordsGoToNew => 28,
            AcCmd::Replace => 29,
            AcCmd::Find => 30,
            AcCmd::RunMacro => 31,
            AcCmd::PageSetup => 32,
            AcCmd::InsertObject => 33,
            AcCmd::Duplicate => 34,
            AcCmd::AboutMicrosoftAccess => 35,
            AcCmd::FormHdrFtr => 36,
            AcCmd::ReportHdrFtr => 37,
            AcCmd::PasteAppend => 38,
            AcCmd::InsertFile => 39,
            AcCmd::SelectForm => 40,
            AcCmd::TabOrder => 41,
            AcCmd::FieldList => 42,
            AcCmd::AlignLeft => 43,
            AcCmd::AlignRight => 44,
            AcCmd::AlignTop => 45,
            AcCmd::AlignBottom => 46,
            AcCmd::AlignToGrid => 47,
            AcCmd::SizeToGrid => 48,
            AcCmd::Options => 49,
            AcCmd::SelectRecord => 50,
            AcCmd::SortingAndGrouping => 51,
            AcCmd::BringToFront => 52,
            AcCmd::SendToBack => 53,
            AcCmd::PrintPreview => 54,
            AcCmd::ApplyDefault => 55,
            AcCmd::SetControlDefaults => 56,
            AcCmd::OLEObjectDefaultVerb => 57,
            AcCmd::Close => 58,
            AcCmd::SizeToFit => 59,
            AcCmd::DocMinimize => 60,
            AcCmd::ViewRuler => 61,
            AcCmd::SnapToGrid => 62,
            AcCmd::ViewGrid => 63,
            AcCmd::PasteSpecial => 64,
            AcCmd::RecordsGoToNext => 65,
            AcCmd::RecordsGoToPrevious => 66,
            AcCmd::RecordsGoToFirst => 67,
            AcCmd::RecordsGoToLast => 68,
            AcCmd::SizeToFitForm => 69,
            AcCmd::EditingAllowed => 70,
            AcCmd::ClearGrid => 71,
            AcCmd::JoinProperties => 72,
            AcCmd::QueryTotals => 73,
            AcCmd::QueryTypeCrosstab => 74,
            AcCmd::TableNames => 75,
            AcCmd::QueryParameters => 76,
            AcCmd::FormatCells => 77,
            AcCmd::DataEntry => 78,
            AcCmd::HideColumns => 79,
            AcCmd::UnhideColumns => 80,
            AcCmd::DeleteQueryColumn => 81,
            AcCmd::InsertQueryColumn => 82,
            AcCmd::RemoveTable => 84,
            AcCmd::ViewToolbox => 85,
            AcCmd::MacroNames => 86,
            AcCmd::MacroConditions => 87,
            AcCmd::SingleStep => 88,
            AcCmd::QueryTypeSelect => 89,
            AcCmd::QueryTypeUpdate => 90,
            AcCmd::QueryTypeAppend => 91,
            AcCmd::QueryTypeDelete => 92,
            AcCmd::ApplyFilterSort => 93,
            AcCmd::QueryTypeMakeTable => 94,
            AcCmd::LoadFromQuery => 95,
            AcCmd::SaveAsQuery => 96,
            AcCmd::SaveRecord => 97,
            AcCmd::AdvancedFilterSort => 99,
            AcCmd::MicrosoftAccessHelpTopics => 100,
            AcCmd::LinkTables => 102,
            AcCmd::UserAndGroupPermissions => 103,
            AcCmd::UserAndGroupAccounts => 104,
            AcCmd::FreezeColumn => 105,
            AcCmd::UnfreezeAllColumns => 106,
            AcCmd::PrimaryKey => 107,
            AcCmd::SubformDatasheet => 108,
            AcCmd::SelectAllRecords => 109,
            AcCmd::ViewTables => 110,
            AcCmd::ViewQueries => 111,
            AcCmd::ViewForms => 112,
            AcCmd::ViewReports => 113,
            AcCmd::ViewMacros => 114,
            AcCmd::ViewModules => 115,
            AcCmd::RowHeight => 116,
            AcCmd::ColumnWidth => 117,
            AcCmd::InsertFileIntoModule => 118,
            AcCmd::SaveModuleAsText => 119,
            AcCmd::FindPrevious => 120,
            AcCmd::WindowSplit => 121,
            AcCmd::ProcedureDefinition => 122,
            AcCmd::DebugWindow => 123,
            AcCmd::Reset => 124,
            AcCmd::CompileAllModules => 125,
            AcCmd::CompileAndSaveAllModules => 126,
            AcCmd::GoContinue => 127,
            AcCmd::StepOver => 128,
            AcCmd::SetNextStatement => 129,
            AcCmd::ShowNextStatement => 130,
            AcCmd::ToggleBreakpoint => 131,
            AcCmd::ClearAllBreakpoints => 132,
            AcCmd::Relationships => 133,
            AcCmd::NewObjectTable => 134,
            AcCmd::NewObjectQuery => 135,
            AcCmd::NewObjectForm => 136,
            AcCmd::NewObjectReport => 137,
            AcCmd::NewObjectMacro => 138,
            AcCmd::NewObjectModule => 139,
            AcCmd::NewObjectClassModule => 140,
            AcCmd::LayoutPreview => 141,
            AcCmd::SaveAsReport => 142,
            AcCmd::Rename => 143,
            AcCmd::RemoveFilterSort => 144,
            AcCmd::SaveLayout => 145,
            AcCmd::ClearAll => 146,
            AcCmd::HideTable => 147,
            AcCmd::ShowDirectRelationships => 148,
            AcCmd::ShowAllRelationships => 149,
            AcCmd::CreateRelationship => 150,
            AcCmd::EditRelationship => 151,
            AcCmd::Indexes => 152,
            AcCmd::AlignToShortest => 153,
            AcCmd::AlignToTallest => 154,
            AcCmd::SizeToNarrowest => 155,
            AcCmd::SizeToWidest => 156,
            AcCmd::HorizontalSpacingMakeEqual => 157,
            AcCmd::HorizontalSpacingDecrease => 158,
            AcCmd::HorizontalSpacingIncrease => 159,
            AcCmd::VerticalSpacingMakeEqual => 160,
            AcCmd::VerticalSpacingDecrease => 161,
            AcCmd::VerticalSpacingIncrease => 162,
            AcCmd::SortAscending => 163,
            AcCmd::SortDescending => 164,
            AcCmd::ToolbarsCustomize => 165,
            AcCmd::OLEObjectConvert => 167,
            AcCmd::QueryTypeSQLDataDefinition => 168,
            AcCmd::QueryTypeSQLPassThrough => 169,
            AcCmd::ViewCode => 170,
            AcCmd::ConvertDatabase => 171,
            AcCmd::CallStack => 172,
            AcCmd::Send => 173,
            AcCmd::OutputToExcel => 175,
            AcCmd::OutputToRTF => 176,
            AcCmd::OutputToText => 177,
            AcCmd::InvokeBuilder => 178,
            AcCmd::ZoomBox => 179,
            AcCmd::QueryTypeSQLUnion => 180,
            AcCmd::Run => 181,
            AcCmd::PageHdrFtr => 182,
            AcCmd::DesignView => 183,
            AcCmd::SQLView => 184,
            AcCmd::ShowTable => 185,
            AcCmd::CloseWindow => 186,
            AcCmd::InsertRows => 187,
            AcCmd::DeleteRows => 188,
            AcCmd::Cut => 189,
            AcCmd::Copy => 190,
            AcCmd::Paste => 191,
            AcCmd::AutoDial => 192,
            AcCmd::NewObjectAutoForm => 193,
            AcCmd::NewObjectAutoReport => 194,
            AcCmd::WordMailMerge => 195,
            AcCmd::TestValidationRules => 196,
            AcCmd::ControlWizardsToggle => 197,
            AcCmd::End => 198,
            AcCmd::Redo => 199,
            AcCmd::ObjectBrowser => 200,
            AcCmd::AddWatch => 201,
            AcCmd::EditWatch => 202,
            AcCmd::QuickWatch => 203,
            AcCmd::StepToCursor => 204,
            AcCmd::Indent => 205,
            AcCmd::Outdent => 206,
            AcCmd::FilterByForm => 207,
            AcCmd::FilterBySelection => 208,
            AcCmd::ViewLargeIcons => 209,
            AcCmd::ViewDetails => 210,
            AcCmd::ViewSmallIcons => 211,
            AcCmd::ViewList => 212,
            AcCmd::LineUpIcons => 213,
            AcCmd::ArrangeIconsByName => 214,
            AcCmd::ArrangeIconsByType => 215,
            AcCmd::ArrangeIconsByCreated => 216,
            AcCmd::ArrangeIconsByModified => 217,
            AcCmd::ArrangeIconsAuto => 218,
            AcCmd::CreateShortcut => 219,
            AcCmd::ToggleFilter => 220,
            AcCmd::OpenTable => 221,
            AcCmd::InsertPicture => 222,
            AcCmd::DeleteRecord => 223,
            AcCmd::StartupProperties => 224,
            AcCmd::PageNumber => 225,
            AcCmd::DateAndTime => 226,
            AcCmd::ChangeToTextBox => 227,
            AcCmd::ChangeToLabel => 228,
            AcCmd::ChangeToListBox => 229,
            AcCmd::ChangeToComboBox => 230,
            AcCmd::ChangeToCheckBox => 231,
            AcCmd::ChangeToToggleButton => 232,
            AcCmd::ChangeToOptionButton => 233,
            AcCmd::ChangeToImage => 234,
            AcCmd::AnswerWizard => 235,
            AcCmd::MicrosoftOnTheWeb => 236,
            AcCmd::ClearItemDefaults => 237,
            AcCmd::Zoom200 => 238,
            AcCmd::Zoom150 => 239,
            AcCmd::Zoom100 => 240,
            AcCmd::Zoom75 => 241,
            AcCmd::Zoom50 => 242,
            AcCmd::Zoom25 => 243,
            AcCmd::Zoom10 => 244,
            AcCmd::FitToWindow => 245,
            AcCmd::PreviewOnePage => 246,
            AcCmd::PreviewTwoPages => 247,
            AcCmd::PreviewFourPages => 248,
            AcCmd::PreviewEightPages => 249,
            AcCmd::PreviewTwelvePages => 250,
            AcCmd::OpenURL => 251,
            AcCmd::OpenStartPage => 252,
            AcCmd::OpenSearchPage => 253,
            AcCmd::RegisterActiveXControls => 254,
            AcCmd::DeleteTab => 255,
            AcCmd::DatabaseProperties => 256,
            AcCmd::Import => 257,
            AcCmd::InsertActiveXControl => 258,
            AcCmd::InsertHyperlink => 259,
            AcCmd::References => 260,
            AcCmd::AutoCorrect => 261,
            AcCmd::InsertProcedure => 262,
            AcCmd::CreateReplica => 263,
            AcCmd::SynchronizeNow => 264,
            AcCmd::RecoverDesignMaster => 265,
            AcCmd::ResolveConflicts => 266,
            AcCmd::DeleteWatch => 267,
            AcCmd::Spelling => 269,
            AcCmd::AutoFormat => 270,
            AcCmd::DeleteTableColumn => 271,
            AcCmd::InsertTableColumn => 272,
            AcCmd::InsertLookupColumn => 273,
            AcCmd::RenameColumn => 274,
            AcCmd::SetDatabasePassword => 275,
            AcCmd::UserLevelSecurityWizard => 276,
            AcCmd::FilterExcludingSelection => 277,
            AcCmd::QuickPrint => 278,
            AcCmd::ConvertMacrosToVisualBasic => 279,
            AcCmd::SaveAllModules => 280,
            AcCmd::FormView => 281,
            AcCmd::DatasheetView => 282,
            AcCmd::AnalyzePerformance => 283,
            AcCmd::AnalyzeTable => 284,
            AcCmd::Documenter => 285,
            AcCmd::TileHorizontally => 286,
            AcCmd::Properties => 287,
            AcCmd::TransparentBackground => 288,
            AcCmd::TransparentBorder => 289,
            AcCmd::CompileLoadedModules => 290,
            AcCmd::InsertLookupField => 291,
            AcCmd::Undo => 292,
            AcCmd::InsertChart => 293,
            AcCmd::GoBack => 294,
            AcCmd::GoForward => 295,
            AcCmd::StopLoadingPage => 296,
            AcCmd::RefreshPage => 297,
            AcCmd::FavoritesOpen => 298,
            AcCmd::FavoritesAddTo => 299,
            AcCmd::ShowOnlyWebToolbar => 300,
            AcCmd::ToolbarControlProperties => 301,
            AcCmd::ShowMembers => 302,
            AcCmd::ListConstants => 303,
            AcCmd::QuickInfo => 304,
            AcCmd::ParameterInfo => 305,
            AcCmd::CompleteWord => 306,
            AcCmd::BookmarksToggle => 307,
            AcCmd::BookmarksNext => 308,
            AcCmd::BookmarksPrevious => 309,
            AcCmd::BookmarksClearAll => 310,
            AcCmd::StepOut => 311,
            AcCmd::FindPrevWordUnderCursor => 312,
            AcCmd::FindNextWordUnderCursor => 313,
            AcCmd::ObjBrwFindWholeWordOnly => 314,
            AcCmd::ObjBrwShowHiddenMembers => 315,
            AcCmd::ObjBrwViewDefinition => 317,
            AcCmd::ObjBrwGroupMembers => 318,
            AcCmd::SelectReport => 319,
            AcCmd::Publish => 320,
            AcCmd::SaveAsHTML => 321,
            AcCmd::SaveAsIDC => 322,
            AcCmd::SaveAsASP => 323,
            AcCmd::PublishDefaults => 324,
            AcCmd::EditHyperlink => 325,
            AcCmd::OpenHyperlink => 326,
            AcCmd::OpenNewHyperlink => 327,
            AcCmd::CopyHyperlink => 328,
            AcCmd::HyperlinkDisplayText => 329,
            AcCmd::TabControlPageOrder => 330,
            AcCmd::InsertPage => 331,
            AcCmd::DeletePage => 332,
            AcCmd::SelectAll => 333,
            AcCmd::CreateMenuFromMacro => 334,
            AcCmd::CreateToolbarFromMacro => 335,
            AcCmd::CreateShortcutMenuFromMacro => 336,
            AcCmd::Delete => 337,
            AcCmd::RunOpenMacro => 338,
            AcCmd::LastPosition => 339,
            AcCmd::Print => 340,
            AcCmd::FindNext => 341,
            AcCmd::StepInto => 342,
            AcCmd::ClearHyperlink => 343,
            AcCmd::DataAccessPageBrowse => 344,
            AcCmd::NewObjectDataAccessPage => 346,
            AcCmd::SelectDataAccessPage => 347,
            AcCmd::ViewDataAccessPages => 349,
            AcCmd::NewObjectView => 350,
            AcCmd::NewObjectStoredProcedure => 351,
            AcCmd::NewObjectDiagram => 352,
            AcCmd::ViewFieldList => 353,
            AcCmd::ViewDiagrams => 354,
            AcCmd::ViewStoredProcedures => 355,
            AcCmd::ViewViews => 356,
            AcCmd::ViewShowPaneSQL => 357,
            AcCmd::ViewShowPaneDiagram => 358,
            AcCmd::ViewShowPaneGrid => 359,
            AcCmd::ViewVerifySQL => 360,
            AcCmd::QueryGroupBy => 361,
            AcCmd::QueryAddToOutput => 362,
            AcCmd::ViewTableColumnNames => 363,
            AcCmd::ViewTableNameOnly => 364,
            AcCmd::HidePane => 365,
            AcCmd::Remove => 366,
            AcCmd::ViewTableColumnProperties => 368,
            AcCmd::ViewTableKeys => 369,
            AcCmd::ViewTableUserView => 370,
            AcCmd::ZoomSelection => 371,
            AcCmd::DiagramNewLabel => 372,
            AcCmd::DiagramAddRelatedTables => 373,
            AcCmd::DiagramShowRelationshipLabels => 374,
            AcCmd::DiagramModifyUserDefinedView => 375,
            AcCmd::DiagramViewPageBreaks => 376,
            AcCmd::DiagramRecalculatePageBreaks => 377,
            AcCmd::DiagramAutosizeSelectedTables => 378,
            AcCmd::DiagramLayoutSelection => 379,
            AcCmd::DiagramLayoutDiagram => 380,
            AcCmd::DiagramNewTable => 381,
            AcCmd::DiagramDeleteRelationship => 382,
            AcCmd::Connection => 383,
            AcCmd::EditTriggers => 384,
            AcCmd::DataAccessPageDesignView => 385,
            AcCmd::Promote => 386,
            AcCmd::GroupByTable => 387,
            AcCmd::Demote => 388,
            AcCmd::SaveAsDataAccessPage => 389,
            AcCmd::MicrosoftScriptEditor => 390,
            AcCmd::WorkGroupAdministrator => 391,
            AcCmd::NewObjectFunction => 394,
            AcCmd::ViewFunctions => 395,
            AcCmd::PivotTableView => 396,
            AcCmd::PivotChartView => 397,
            AcCmd::PivotAutoFilter => 398,
            AcCmd::PivotTableSubtotal => 399,
            AcCmd::PivotCollapse => 400,
            AcCmd::PivotExpand => 401,
            AcCmd::PivotTableHideDetails => 402,
            AcCmd::PivotTableShowDetails => 403,
            AcCmd::PivotRefresh => 404,
            AcCmd::PivotTableExportToExcel => 405,
            AcCmd::PivotTableMoveToRowArea => 406,
            AcCmd::PivotTableMoveToColumnArea => 407,
            AcCmd::PivotTableMoveToFilterArea => 408,
            AcCmd::PivotTableMoveToDetailArea => 409,
            AcCmd::PivotTablePromote => 410,
            AcCmd::PivotTableDemote => 411,
            AcCmd::PivotAutoSum => 412,
            AcCmd::PivotAutoCount => 413,
            AcCmd::PivotAutoMin => 414,
            AcCmd::PivotAutoAverage => 416,
            AcCmd::PivotAutoStdDev => 417,
            AcCmd::PivotAutoVar => 418,
            AcCmd::PivotAutoStdDevP => 419,
            AcCmd::PivotAutoVarP => 420,
            AcCmd::PivotShowTop1 => 421,
            AcCmd::PivotShowTop2 => 422,
            AcCmd::PivotShowTop5 => 423,
            AcCmd::PivotShowTop10 => 424,
            AcCmd::PivotShowTop25 => 425,
            AcCmd::PivotShowTop1Percent => 426,
            AcCmd::PivotShowTop2Percent => 427,
            AcCmd::PivotShowTop5Percent => 428,
            AcCmd::PivotShowTop10Percent => 429,
            AcCmd::PivotShowTop25Percent => 430,
            AcCmd::PivotShowTopOther => 431,
            AcCmd::PivotShowBottom1 => 432,
            AcCmd::PivotShowBottom2 => 433,
            AcCmd::PivotShowBottom5 => 434,
            AcCmd::PivotShowBottom10 => 435,
            AcCmd::PivotShowBottom25 => 436,
            AcCmd::PivotShowBottom1Percent => 437,
            AcCmd::PivotShowBottom2Percent => 438,
            AcCmd::PivotShowBottom5Percent => 439,
            AcCmd::PivotShowBottom10Percent => 440,
            AcCmd::PivotShowBottom25Percent => 441,
            AcCmd::PivotShowBottomOther => 442,
            AcCmd::PivotTableCreateCalcTotal => 443,
            AcCmd::PivotTableCreateCalcField => 444,
            AcCmd::PivotTableShowAsNormal => 445,
            AcCmd::PivotTablePercentRowTotal => 446,
            AcCmd::PivotTablePercentColumnTotal => 447,
            AcCmd::PivotTablePercentParentRowItem => 448,
            AcCmd::PivotTablePercentParentColumnItem => 449,
            AcCmd::PivotTablePercentGrandTotal => 450,
            AcCmd::PivotTableExpandIndicators => 451,
            AcCmd::PivotDropAreas => 452,
            AcCmd::PivotChartType => 453,
            AcCmd::PivotDelete => 454,
            AcCmd::PivotChartShowLegend => 455,
            AcCmd::PivotChartByRowByColumn => 456,
            AcCmd::PivotChartDrillInto => 457,
            AcCmd::PivotMultiplePlots => 458,
            AcCmd::PivotMultiplePlotsUnifiedScale => 459,
            AcCmd::PivotChartUndo => 460,
            AcCmd::PivotShowAll => 461,
            AcCmd::SubformFormView => 462,
            AcCmd::SubformDatasheetView => 463,
            AcCmd::SubformPivotTableView => 464,
            AcCmd::SubformPivotChartView => 465,
            AcCmd::WebPagePreview => 466,
            AcCmd::PageProperties => 467,
            AcCmd::DataOutline => 468,
            AcCmd::InsertMovieFromFile => 469,
            AcCmd::InsertPivotTable => 470,
            AcCmd::InsertSpreadsheet => 471,
            AcCmd::InsertUnboundSection => 472,
            AcCmd::WebTheme => 473,
            AcCmd::BackgroundPicture => 474,
            AcCmd::BackgroundSound => 475,
            AcCmd::AlignMiddle => 476,
            AcCmd::AlignCenter => 477,
            AcCmd::AlignmentAndSizing => 478,
            AcCmd::DataAccessPageFieldListRefresh => 479,
            AcCmd::DataAccessPageAddToPage => 480,
            AcCmd::Zoom500 => 481,
            AcCmd::Zoom1000 => 482,
            AcCmd::PrintRelationships => 483,
            AcCmd::GroupControls => 484,
            AcCmd::UngroupControls => 485,
            AcCmd::WebPageProperties => 486,
            AcCmd::Export => 487,
            AcCmd::OfficeClipboard => 488,
            AcCmd::DeleteTable => 489,
            AcCmd::PasteAsHyperlink => 490,
            AcCmd::NewGroup => 491,
            AcCmd::RenameGroup => 492,
            AcCmd::DeleteGroup => 493,
            AcCmd::AddToNewGroup => 494,
            AcCmd::SubformInNewWindow => 495,
            AcCmd::ServerProperties => 496,
            AcCmd::TableCustomView => 497,
            AcCmd::TableAddTable => 498,
            AcCmd::InsertSubdatasheet => 499,
            AcCmd::ConditionalFormating => 500,
            AcCmd::ChangeToCommandButton => 501,
            AcCmd::SubdatasheetRemove => 506,
            AcCmd::ServerFilterByForm => 507,
            AcCmd::MaximumRecords => 508,
            AcCmd::Speech => 511,
            AcCmd::Backup => 513,
            AcCmd::Restore => 514,
            AcCmd::SubdatasheetCollapseAll => 515,
            AcCmd::CopyDatabaseFile => 516,
            AcCmd::DropSQLDatabase => 517,
            AcCmd::LinkedTableManager => 519,
            AcCmd::DatabaseSplitter => 520,
            AcCmd::SwitchboardManager => 521,
            AcCmd::UpsizingWizard => 522,
            AcCmd::PartialReplicaWizard => 524,
            AcCmd::VisualBasicEditor => 525,
            AcCmd::AddInManager => 526,
            AcCmd::PivotTableClearCustomOrdering => 527,
            AcCmd::PivotTableFilterBySelection => 528,
            AcCmd::PivotTableRemove => 529,
            AcCmd::PivotTableGroupItems => 530,
            AcCmd::PivotTableUngroupItems => 531,
            AcCmd::PivotChartDrillOut => 532,
            AcCmd::ShowEnvelope => 533,
            AcCmd::PivotChartSortAscByTotal => 534,
            AcCmd::PivotChartSortDescByTotal => 535,
            AcCmd::ViewObjectDependencies => 536,
            AcCmd::PublishDatabase => 537,
            AcCmd::CloseDatabase => 538,
            AcCmd::ReportView => 539,
            AcCmd::ToggleOffline => 540,
            AcCmd::RefreshData => 541,
            AcCmd::ShareOnSharePoint => 542,
            AcCmd::SavedImports => 543,
            AcCmd::ImportAttachAccess => 544,
            AcCmd::ImportAttachExcel => 545,
            AcCmd::ImportAttachText => 546,
            AcCmd::ImportAttachSharePointList => 547,
            AcCmd::ImportAttachXML => 548,
            AcCmd::ImportAttachODBC => 549,
            AcCmd::ImportAttachHTML => 550,
            AcCmd::ImportAttachOutlook => 551,
            AcCmd::ImportAttachdBase => 552,
            AcCmd::ImportAttachParadox => 553,
            AcCmd::ImportAttachLotus => 554,
            AcCmd::SavedExports => 555,
            AcCmd::ExportExcel => 556,
            AcCmd::ExportSharePointList => 557,
            AcCmd::ExportRTF => 558,
            AcCmd::ExportAccess => 559,
            AcCmd::ExportText => 560,
            AcCmd::ExportXML => 561,
            AcCmd::ExportODBC => 562,
            AcCmd::ExportSnapShot => 563,
            AcCmd::ExportHTML => 564,
            AcCmd::ExportdBase => 565,
            AcCmd::ExportParadox => 566,
            AcCmd::ExportLotus => 567,
            AcCmd::StackedLayout => 568,
            AcCmd::TabularLayout => 569,
            AcCmd::SelectEntireRow => 570,
            AcCmd::SelectEntireColumn => 571,
            AcCmd::MoveColumnCellUp => 572,
            AcCmd::MoveColumnCellDown => 573,
            AcCmd::LayoutGridlinesBoth => 574,
            AcCmd::LayoutGridlinesVertical => 575,
            AcCmd::LayoutGridlinesHorizontal => 576,
            AcCmd::LayoutGridlinesNone => 577,
            AcCmd::LayoutGridlinesCrossHatch => 578,
            AcCmd::LayoutGridlinesTop => 579,
            AcCmd::LayoutGridlinesBottom => 580,
            AcCmd::LayoutGridlinesOutline => 581,
            AcCmd::RemoveFromLayout => 582,
            AcCmd::AddFromOutlook => 583,
            AcCmd::SaveAsOutlookContact => 584,
            AcCmd::InsertLogo => 585,
            AcCmd::InsertTitle => 586,
            AcCmd::PasteFormatting => 587,
            AcCmd::MacroArguments => 588,
            AcCmd::MacroAllActions => 589,
            AcCmd::PrintSelection => 590,
            AcCmd::PublishFixedFormat => 591,
            AcCmd::ExportFixedFormat => 592,
            AcCmd::LayoutView => 593,
            AcCmd::NewObjectContinuousForm => 594,
            AcCmd::NewObjectSplitForm => 595,
            AcCmd::NewObjectPivotChart => 596,
            AcCmd::NewObjectPivotTable => 597,
            AcCmd::NewObjectDatasheetForm => 598,
            AcCmd::NewObjectModalForm => 599,
            AcCmd::NewObjectBlankForm => 600,
            AcCmd::NewObjectLabelsReport => 601,
            AcCmd::NewObjectBlankReport => 602,
            AcCmd::NewObjectDesignQuery => 603,
            AcCmd::NewObjectDesignForm => 604,
            AcCmd::NewObjectDesignReport => 605,
            AcCmd::NewObjectDesignTable => 606,
            AcCmd::EditListItems => 607,
            AcCmd::ManageReplies => 609,
            AcCmd::AnchorTopLeft => 610,
            AcCmd::AnchorStretchAcross => 611,
            AcCmd::AnchorTopRight => 612,
            AcCmd::AnchorStretchDown => 613,
            AcCmd::AnchorStretchDownAcross => 614,
            AcCmd::AnchorStretchDownRight => 615,
            AcCmd::AnchorBottomLeft => 616,
            AcCmd::AnchorBottomStretchAcross => 617,
            AcCmd::AnchorBottomRight => 618,
            AcCmd::FilterMenu => 619,
            AcCmd::ShowColumnHistory => 620,
            AcCmd::BrowseSharePointList => 621,
            AcCmd::ModifySharePointList => 622,
            AcCmd::ModifySharePointListAlerts => 623,
            AcCmd::ModifySharePointListWorkflow => 624,
            AcCmd::ModifySharePointListPermissions => 625,
            AcCmd::RefreshSharePointList => 626,
            AcCmd::DeleteSharePointList => 627,
            AcCmd::ControlMarginsNone => 628,
            AcCmd::ControlMarginsNarrow => 629,
            AcCmd::ControlMarginsMedium => 630,
            AcCmd::ControlMarginsWide => 631,
            AcCmd::ControlPaddingNone => 632,
            AcCmd::ControlPaddingNarrow => 633,
            AcCmd::ControlPaddingMedium => 634,
            AcCmd::ControlPaddingWide => 635,
            AcCmd::ShowDatePicker => 636,
            AcCmd::SetCaption => 637,
            AcCmd::Synchronize => 638,
            AcCmd::DiscardChanges => 639,
            AcCmd::DiscardChangesAndRefresh => 640,
            AcCmd::SharePointSiteRecycleBin => 641,
            AcCmd::ToggleCacheListData => 642,
            AcCmd::RemoveFilterFromCurrentColumn => 643,
            AcCmd::RemoveAllFilters => 644,
            AcCmd::RemoveAllSorts => 645,
            AcCmd::CloseAll => 646,
            AcCmd::FieldTemplates => 647,
            AcCmd::ApplyAutoFormat1 => 648,
            AcCmd::ApplyAutoFormat2 => 649,
            AcCmd::ApplyAutoFormat3 => 650,
            AcCmd::ApplyAutoFormat4 => 651,
            AcCmd::ApplyAutoFormat5 => 652,
            AcCmd::ApplyAutoFormat6 => 653,
            AcCmd::ApplyAutoFormat7 => 654,
            AcCmd::ApplyAutoFormat8 => 655,
            AcCmd::ApplyAutoFormat9 => 656,
            AcCmd::ApplyAutoFormat10 => 657,
            AcCmd::ApplyAutoFormat11 => 658,
            AcCmd::ApplyAutoFormat12 => 659,
            AcCmd::ApplyAutoFormat13 => 660,
            AcCmd::ApplyAutoFormat14 => 661,
            AcCmd::ApplyAutoFormat15 => 662,
            AcCmd::ApplyAutoFormat16 => 663,
            AcCmd::ApplyAutoFormat17 => 664,
            AcCmd::ApplyAutoFormat18 => 665,
            AcCmd::ApplyAutoFormat20 => 667,
            AcCmd::ApplyAutoFormat21 => 668,
            AcCmd::ApplyAutoFormat22 => 669,
            AcCmd::ApplyAutoFormat23 => 670,
            AcCmd::ApplyAutoFormat24 => 671,
            AcCmd::ApplyAutoFormat25 => 672,
            AcCmd::ManageAttachments => 673,
            AcCmd::WorkflowTasks => 674,
            AcCmd::StartNewWorkflow => 675,
            AcCmd::ShowMessageBar => 676,
            AcCmd::HideMessageBar => 677,
            AcCmd::LayoutInsertRowAbove => 678,
            AcCmd::LayoutInsertRowBelow => 679,
            AcCmd::LayoutInsertColumnLeft => 680,
            AcCmd::LayoutInsertColumnRight => 681,
            AcCmd::LayoutMergeCells => 682,
            AcCmd::LayoutSplitColumnCell => 683,
            AcCmd::LayoutSplitRowCell => 684,
            AcCmd::ShowLogicCatalog => 685,
            AcCmd::SaveAsTemplate => 686,
            AcCmd::SaveDatabaseAsNewTemplatePart => 687,
            AcCmd::SaveSelectionAsNewDataType => 688,
            AcCmd::NewObjectNavigationTop => 689,
            AcCmd::NewObjectNavigationLeft => 690,
            AcCmd::NewObjectNavigationRight => 691,
            AcCmd::NewObjectNavigationTopTop => 692,
            AcCmd::NewObjectNavigationTopLeft => 693,
            AcCmd::NewObjectNavigationTopRight => 694,
            AcCmd::CompatCheckDatabase => 695,
            AcCmd::CompatCheckCurrentObject => 696,
            AcCmd::DesignObject => 697,
            AcCmd::CalculatedColumn => 698,
            AcCmd::SyncWebApplication => 699,
            AcCmd::ConvertLinkedTableToLocal => 700,
            AcCmd::NewObjectContinuousFormWeb => 701,
            AcCmd::NewObjectDatasheetFormWeb => 702,
            AcCmd::NewObjectBlankFormWeb => 703,
            AcCmd::NewObjectBlankReportWeb => 704,
            AcCmd::NewObjectAutoFormWeb => 705,
            AcCmd::NewObjectAutoReportWeb => 706,
            AcCmd::NewObjectQueryWeb => 707,
            AcCmd::NewObjectMacroWeb => 708,
            AcCmd::NewObjectNavigationTopWeb => 709,
            AcCmd::NewObjectNavigationLeftWeb => 710,
            AcCmd::NewObjectNavigationRightWeb => 711,
            AcCmd::NewObjectNavigationTopTopWeb => 712,
            AcCmd::NewObjectNavigationTopLeftWeb => 713,
            AcCmd::NewObjectNavigationTopRightWeb => 714,
            AcCmd::SelectEntireLayout => 715,
            AcCmd::PrepareDatabaseForWeb => 716,
            AcCmd::ManageTableEvents => 717,
            AcCmd::AddDataMacroAfterInsert => 718,
            AcCmd::AddDataMacroAfterDelete => 720,
            AcCmd::AddDataMacroValidateDelete => 721,
            AcCmd::AddDataMacroValidateChange => 722,
            AcCmd::AddNamedDataMacro => 723,
            AcCmd::InsertNavigationButton => 724,
            AcCmd::Unknown(n) => n,
        }
    }
}

impl From<AcCmd> for u16 {
    fn from(c: AcCmd) -> u16 {
        c.code()
    }
}
